import eyeImgClose from './../images/closeEye.png'
import eyeImgActive from './../images/openEye.png'

export const regexpPatterns = {
    email:/([a-zA-Z0-9]+[\.|_|\-]*)*@gmail\.(com|es)?/g
}

export const signUpData = [
    {
        labelName: 'First Name',
        labelClassName: 'label',
        keyName: 'firstName',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputErrorField',
        inputType: 'text', 
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
    },
    {
        labelName: 'Last Name',
        labelClassName: 'label',
        keyName: 'lastName',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputField',
        inputType: 'password', 
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
    },
    {
        labelName: 'Email',
        labelClassName: 'label',
        keyName: 'email',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputErrorField',
        inputType: 'text', 
        validate: regexpPatterns.email,
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
    },
    {
        labelName: 'Password',
        labelClassName: 'label',
        keyName: 'password',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputField',
        inputType: 'password', 
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
        inputContainerClassName: 'inputErrorFieldContainer',
        isActiveEye: true,
        eyeClassName: 'eyeStyle',
        closeEyeImage: eyeImgClose,
        activeEyeImage: eyeImgActive,
    },
    {
        labelName: 'Confirm password',
        dataComparison: 'password',
        dataComparisonError: 'this passwords no match',
        labelClassName: 'label',
        keyName: 'confirmedPassword',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputField',
        inputType: 'password', 
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
        inputContainerClassName: 'inputErrorFieldContainer',
        isActiveEye: true,
        eyeClassName: 'eyeStyle',
        closeEyeImage: eyeImgClose,
        activeEyeImage: eyeImgActive,
    },
]

export const signInData = [
    {
        labelName: 'Email',
        labelClassName: 'label',
        keyName: 'email',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputErrorField',
        inputType: 'text', 
        validate: regexpPatterns.email,
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
    },
    {
        labelName: 'Password',
        labelClassName: 'label',
        keyName: 'password',
        state: '',
        inputClassName:'inputField',
        inputErrorClassName:'inputField',
        inputType: 'password', 
        errorClassName: 'error',
        errorText: 'bla bla email', 
        error: '',
        isNecessarily: true,
        wrapperClassName: 'formElementContainer',
        inputContainerClassName: 'inputErrorFieldContainer',
        isActiveEye: true,
        eyeClassName: 'eyeStyle',
        closeEyeImage: eyeImgClose,
        activeEyeImage: eyeImgActive,
    },
]